default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    <<: *default
    database: umanni_development
  queue:
    <<: *default
    database: umanni_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: umanni_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: umanni_test
production:
  primary: &primary_production
    <<: *default
    database: umanni_production
    username: umanni
    password: <%= ENV["UMANNI_DATABASE_PASSWORD"] %>
  queue:
    <<: *primary_production
    database: umanni_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: umanni_production_cable
    migrations_paths: db/cable_migrate
